# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71c27f7f55d345811bb6e05c0ac2a696"
name = "A/B-Test-Navigation"
application_url = "https://requesting-services-trim-d.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tlx-new-brand.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://requesting-services-trim-d.trycloudflare.com/auth/callback",
  "https://requesting-services-trim-d.trycloudflare.com/auth/shopify/callback",
  "https://requesting-services-trim-d.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
